### ISSUE TITLE
unable to download the model onnx_modifier is not defined

### ISSUE THREAD

**Issue by SimpleTon23** [ZhangGe6/onnx-modifier#80] opened 2023-09-19 12:34 UTC
<img width="701" alt="image" src="https://github.com/ZhangGe6/onnx-modifier/assets/143125713/54fd7564-e829-4c72-afaa-9f45c1187c58">
I haven't chaned anything , opened the onnx file and trying to click download and i am getting this error. Can you help why this is happening

**Comment by ZhangGe6** [comment] 2023-09-19 23:31
@SimpleTon23 Thanks for reporting. Can you share the full error log?

**Comment by ZhangGe6** [comment] 2023-09-23 14:07
@SimpleTon23 Thanks for reporting. Which platform are you using? I have tried Windows, MacOS, and Ubuntu(16.04), but can not reproduce this issue.

**Comment by beingjoey** [comment] 2023-10-27 02:41
the same error, in windows docker.

**Comment by Egorundel** [comment] 2023-10-30 07:22
The same error on Ubuntu 16.04. Is the problem not solved yet?

**Comment by Egorundel** [comment] 2023-10-30 07:46
The problem was solved quite simply: just downgrade the onnx version. I installed `pip install onnx==1.12.0` and everything worked for me without errors.

**Comment by ZhangGe6** [comment] 2023-10-31 04:46
@beingjoey Thanks for clarifying! 

@SimpleTon23 @beingjoey Please check the Python package versions. If this issue is caused by Python package versions, the following version config should work:
```
onnx==1.13.0
flask==2.2.5
onnx-tool==0.8.1
```

**Comment by Egorundel** [comment] 2023-10-31 07:17
@ZhangGe6 I wrote the explanation 😂 😂 😂

**Comment by ZhangGe6** [comment] 2023-11-01 04:26
> @ZhangGe6 I wrote the explanation 😂 😂 😂

@Egorundel haha, thanks for clarifying again.

**Comment by ZhangGe6** [comment] 2023-11-12 13:26
I am going to close the issue. Feel free to reopen it if the problem still exists.

**Closed by ZhangGe6** 2023-11-12 13:26 UTC
